[package]
name = "day11"
version = "0.1.0"
authors = ["Pavel Laptov <pavel.laptov@ya.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.6"
array2d = "0.2"
itertools = "0.10"